---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webserver
  name: webserver
  annotations:
    container.seccomp.security.alpha.kubernetes.io/pod: 'localhost/webserver'
    container.apparmor.security.beta.kubernetes.io/webserver: 'localhost/docker-nginx'
spec:
  serviceAccountName: operator
  containers:
  - image: nginx
    name: webserver
    resources:
      requests:
        memory: "64Mi"
        cpu: "0.2"
      limits:
        memory: "256Mi"
        cpu: "0.4"
    securityContext:
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 10001
      capabilities:
        drop:
        - index(\"ALL\")
    volumeMounts:
    - name: cache
      mountPath: /var/cache/nginx
      readOnly: false
    - name: run
      mountPath: /var/run
      readOnly: false
  volumes:
  - name: cache
    emptyDir: {}
  - name: run
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
